### ISSUE TITLE
min-item-height problem

### ISSUE THREAD

**Issue by AceLing** [Akryum/vue-virtual-scroller#104]
@Akryum Hello!
First of all thanks for your great work! It's userful for my program.

I am using the **DynamicScroller** component and set its minItemHeight 36px as required.
As you say: 
> minItemHeight is required for the initial render of items.

Then I add an element with 79px height (or unknown height) and emit **scrollToItem** function but its position is not correct.
I view the **console** and find that the component seems to calculate the element(unknown height)'s height as the minItemHeight.

How can I fix this problem?
I am looking forward to your suggestion.
Thanks a lot.

**Comment by betatester07** [comment]
It looks to me that the problem occours because when you add items the `forceUpdate` method is triggered before `itemsWithHeight` computed property is recalculated (because watcher is executed before computed properties are updated). Therefore, the new / updated items won't be included and calculated.

I fixed it by executing `forceUpdate` only after `itemsWithHeight` have been recalculated in `DynamicScroller.vue`, [see my commit](https://github.com/Akryum/vue-virtual-scroller/compare/master...betatester07:fix104#diff-a11529d99967a81d7d8b1eb876ab4ca0).

@Akryum do you think the change could have some side effects? If it is OK I can PR

**Comment by alejandroiglesias** [comment]
@betatester07 please open a PR to try to move this forward. This issue popped up after 10 mins of playing around with the `DynamicScroller`, so it seems something important to fix fast @Akryum?

**Comment by betatester07** [comment]
I just noticed that Akryum released new version few days ago (see [v1.0.0-beta.5](https://github.com/Akryum/vue-virtual-scroller/releases/tag/v1.0.0-beta.5)), including [this commit](https://github.com/Akryum/vue-virtual-scroller/commit/c642fa2c4444b30e230bc1a962540431d6605c05) - I don't have time to test it right now but quickly looking at the code it could at least mitigate the issue in some cases.

@alejandroiglesias Have you tried the latest version?

**Comment by alejandroiglesias** [comment]
@betatester07 sorry, I realized that my issue was related to incorrectly setting the height of the `DynamicScroller` to the actual available space. After some CSS adjustment to make the `DynamicScroller` use the available space so that `overflow-y: auto` property takes effect, the issue was gone. So it was unrelated to your issue. I'm also using `v1.0.0-beta.5` and saw no other issues after having fixed this.

**Comment by betatester07** [comment]
@alejandroiglesias no problem, glad you have your issue resolved

**Comment by betatester07** [comment]
unfortunately, v1.0.0-beta.5 does not fix my issue. See [this codepen](https://codepen.io/anon/pen/JxBVYr) for demonstration - there are 200 items, after pressing filter button with value '10' it will show only items containing '10' in their name and NOT recompute the height of the newly filtered items, but after scrolling up and down it will update heights correctly.

**Comment by Akryum** [comment]
@betatester07 It should be fixed in the upcoming beta.6

**Comment by betatester07** [comment]
yep, works for me with latest [v1.0.0-rc.1](https://github.com/Akryum/vue-virtual-scroller/releases/tag/v1.0.0-rc.1).

:+1:  for adding filtering example to your demo
